### ISSUE TITLE
xclip: -selection clipboard: No such file or directory

### ISSUE THREAD

**Issue by michaelhaaf** [ayushnix/pass-tessen#1]
**System properties:**
pass-tessen version: 1.5.3 (git clone of latest)
OS: Archcraft x86_64 
Bash: version 5.1.16
WM: openbox
Display server: x11

**Steps to reproduce:**
Using an X11 server, the main "copy to clipboard" behavior doesn't quite work:

`pass tessen

...

xclip: -selection clipboard: No such file or directory

Copied username to clipboard. Will clear in 45 seconds.
`

While the "Copied username" message is reported, the clipboard does not actually contain the username due to the previous error. The culprit is line 143 of tessen.bash:

`
143     printf '%s' "${1-}" | "$TSN_CLIP_CMD" "${TSN_CLIP_CMD_ARGS[*]-}"
`

I'm not a bash expert, but I believe the error has something to do with storing commands as variables rather than as arrays (http://mywiki.wooledge.org/BashFAQ/050). I have applied the following fix on my local version of pass-tessen:

`
143     printf '%s' "${1-}" | "$TSN_CLIP_CMD" "${TSN_CLIP_CMD_ARGS[@]}"
`

This fix has resolved the issue with this function.

I have noticed that same idiom for storing/referencing command args is used throughout this script, and I have not investigated much further than this.

**Comment by ayushnix** [comment]
Thanks for reporting this issue. `pass-tessen` was probably my first shell script project and its due for an overhaul. I need to borrow some code from [tessen](https://github.com/ayushnix/tessen) and do some refactoring. I'll add this bug to the list of fixes that I have to make in `pass-tessen`.

**Comment by ayushnix** [comment]
@michaelhaaf Can you confirm if this issue is fixed in the latest commit?

**Comment by ayushnix** [comment]
The [latest release](https://github.com/ayushnix/pass-tessen/releases/tag/v2.0.1) should've fixed this issue. Let me know if something's not right.

**Comment by michaelhaaf** [comment]
Just updated from AUR, works great. Thanks!
